
### Registrar un usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "Vicaag6",
    "password": "messi2003",
    "email": "rubialoca@gmail.com",
    "enterprise": 1,
    "user_type": 1
}



### Logear un usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "prueba",
    "password": "prueba123"
}


#### Enviar licitacion
POST http://localhost:3000/send/txt

### Ver licitaciones
GET http://localhost:3000/application