
### Registrar un usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "Vicaag6",
    "password": "messi2003",
    "email": "rubialoca@gmail.com",
    "enterprise": 1,
    "user_type": 1
}



### Logear un usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "idiar16@gmail.com",
    "password": "16012004"
}

### Logear un usuario
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "jubertperez@gmail.com",
    "password": "ponganos20"
}

### Cerrar sesion
POST http://localhost:3000/auth/logout



#### Enviar licitacion
POST http://localhost:3000/send/txt
Content-Type: application/json

{
    "title": "Licitacion de prueba",
    "description": "Esta es una licitacion de prueba"
}

### Ver licitaciones
GET http://localhost:3000/application/admin

### Ver licitaciones de un usuario
GET http://localhost:3000/application/user/


### Descargar licitaciones
GET http://localhost:3000/application/download/28